function config = solar_system()

    % Define physical and simulation constants
    config.G = 6.674e-11; % Universal gravitational constant
    AU = 1.496e11;        % Astronomical Unit in meters


    % SUN
    sun = Body('Mass', 1.989e30, ...
               'Position', [0, 0], ...
               'Velocity', [0, 0], ...
               'Color', 'y', ...
               'Size', 30);

    % EARTH
    earth = Body('Mass', 5.972e24, ...
                 'Position', [-1 * AU, 0], ...
                 'Velocity', [0, 29780.0], ...
                 'Color', 'b', ...
                 'Size', 15);

    % MARS
    mars = Body('Mass', 6.39e23, ...
                'Position', [-1.524 * AU, 0], ...
                'Velocity', [0, 24070.0], ...
                'Color', 'r', ...
                'Size', 12);
    
    % Package bodies into a cell array for the config struct
    config.bodies = {sun, earth, mars};
end